name: detection_app
description: Medical Detection Application

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI & Utilities
  google_fonts: ^6.1.0       # สำหรับ Font สวยๆ
  intl: ^0.19.0              # สำหรับจัดการวันที่
  table_calendar: ^3.1.0     # ปฏิทินในหน้า Dashboard
  image_picker: ^1.0.7       # เลือกรูปจาก Gallery
  camera: ^0.10.5+9          # ใช้งานกล้อง
  path_provider: ^2.1.2      # จัดการไฟล์
  path: ^1.9.0
  gal: ^2.2.0                # บันทึกรูปไปยัง Gallery (ทันสมัยกว่า)
  permission_handler: ^12.0.1 # ขออนุญาตเข้าถึง storage
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  dio: ^5.4.0                # ยิง API (ดีกว่า http)
  shared_preferences: ^2.2.2 # เก็บ Token Login

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png